import { DashboardData } from './dashboard-data.service';

export const DashboardMockData: DashboardData[] = [
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
  {
    currentTimestamp: new Date(),
    createdAt: new Date(),
    customerDirection: 'buy',
    coinhakoDirection: 'short',
    price: 1.378414071,
    counter: 'SGD',
    usd: -1.48,
    sgdAmount: 2.04,
    runningPnL: 0.0,
    averageRate: 0.0000037,
    check: true,
  },
];
